### ISSUE TITLE
ami image nullpointer

### ISSUE THREAD

**Issue by mtdunstan** [the-grey-group/open-battery#7]
```
ami -p 3battery image

Generic values (AMIImageTool)
================================
-v to see generic values

Specific values (AMIImageTool)
================================


Generic values (AMIFilterTool)
================================
java.lang.NullPointerException
	at org.contentmine.ami.tools.AbstractAMITool.getCProjectDirectory(AbstractAMITool.java:402)
	at org.contentmine.ami.tools.AbstractAMITool.validateCProject(AbstractAMITool.java:246)
	at org.contentmine.ami.tools.AbstractAMITool.parseGenerics(AbstractAMITool.java:218)
	at org.contentmine.ami.tools.AbstractAMITool.runCommands(AbstractAMITool.java:195)
	at org.contentmine.ami.tools.AMIImageTool.runPrevious(AMIImageTool.java:373)
	at org.contentmine.ami.tools.AbstractAMITool.runCommands(AbstractAMITool.java:203)
	at org.contentmine.ami.tools.AbstractAMITool.call(AbstractAMITool.java:185)
	at org.contentmine.ami.tools.AbstractAMITool.call(AbstractAMITool.java:32)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at org.contentmine.ami.tools.AMI.main(AMI.java:103)
```

**Comment by petermr** [comment]
You may have an old version.
Please update and retry `git pull`
